---
- name: Restart traefik
  community.docker.docker_compose_v2:
    project_src: /opt/traefik
    state: restarted

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
